### ISSUE TITLE
yellow_dn mismatch

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/data#5]
data\skyboxes\yellow_dn.jpg does not match the rest of the skybox. I tried rotating it, but it's actually a color issue. Good luck to anyone good enough with The GIMP to fix this.

![20150222094954](https://cloud.githubusercontent.com/assets/6363417/6318947/60cac71c-ba78-11e4-83ab-51a3672e4f3c.jpg)

**Comment by IceflowRE** [comment]
https://github.com/IceflowRE/data/commit/896231b6e15bcab7d5866967194b60fada1670dc

fixed :)
(but i think i should open a new branch before... but then i must download the whole data.. or? idk )

**Comment by Croydon** [comment]
You don't have to download the whole data again just because you're creating a new branch. When you have the repository, you have already all files ;)

**Comment by IceflowRE** [comment]
Thats the confusing with this repos..... on windows i have one file and can change the content with one click........

**Comment by freezurbern** [comment]
IceflowRE@896231b doesn't look correct either.

---
![iceflower-new_yellow-nogood](https://cloud.githubusercontent.com/assets/6363417/6566148/cd617f36-c68c-11e4-9723-5179ad8a8a99.jpg)

**Comment by IceflowRE** [comment]
Huh? Then i cant correct it because i dont see that difference at me.
![20150310122820](https://cloud.githubusercontent.com/assets/10883690/6574125/a8a0d2e2-c721-11e4-96ea-6b2cb21faf2c.png)
![20150310122822](https://cloud.githubusercontent.com/assets/10883690/6574126/a8ce517c-c721-11e4-843c-d30aee13e2ed.png)
![20150310122825](https://cloud.githubusercontent.com/assets/10883690/6574127/a8d18108-c721-11e4-9c00-51c8740a4478.png)
![20150310122515](https://cloud.githubusercontent.com/assets/10883690/6574128/a8d49b72-c721-11e4-870b-7a13dbd434a4.png)
![20150310122817](https://cloud.githubusercontent.com/assets/10883690/6574129/a8d9f59a-c721-11e4-9c63-d45cecbb0d69.png)

**Comment by qreeves** [comment]
Close enough.

**Comment by IceflowRE** [comment]
Its already done.
https://github.com/red-eclipse/data/commit/613bda43e09e3fcebc2aa64634d63721470429db

**Comment by qreeves** [comment]
Oh sorry didn't notice.
